services:
  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27019:27019"
    volumes:
      - mongo-data:/data/db
    restart: always
    command: --port 27019


volumes:
  mongo-data: